trigger:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: deployment
      type: git
      name: tapio/tapio.Deployment

pr: none

pool:
  vmImage: ubuntu-20.04

jobs:
- template: BuildTemplates/jobs/whitesource.yml@deployment
  parameters:
    productName: github.com/tapioone
    projectName: github.com/tapioone/tapio-auth-react
    scanDirectory: $(System.DefaultWorkingDirectory)
    preSteps:
      - task: NodeTool@0 
        inputs:
          versionSpec: 12.x

      - script: yarn install --frozen-lockfile
