trigger:
  branches:
    include:
      - master

pr: none

pool:
  vmImage: ubuntu-20.04

steps:
  - checkout: self
    clean: true

  - task: NodeTool@0 
    inputs:
      versionSpec: 12.x

  - script: yarn install --frozen-lockfile

  - task: WhiteSource@21
    displayName: "WhiteSource Scan"
    inputs:
      projectName: github.com/tapioone/tapio-auth-react
      cwd: $(System.DefaultWorkingDirectory)
