---
name: "Close stale issues and pull-requests"

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 42 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
        stale-pr-message: 'This pull request is stale because it has been open 42 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
        days-before-stale: 42
        days-before-close: 7
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-pr'
